--.tao bang CUSTOMER 
CREATE TABLE CUSTOMER (
    CUSID            VARCHAR2(10) NOT NULL,
    CUSNAME      VARCHAR2(50),
    CUSADD        VARCHAR2(400),
    CUSMOBILE   VARCHAR2(25),
    CUSEMAIL     VARCHAR2(100),
    PRIMARY KEY (CUSID)
); 
--INSERT
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1773',	'Nguyen Thi Hue',	'731 Tran Hung Dao, Q5, TpHCM','	0947388089','	nguyenhue@gmail.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1782','	Le Anh Duc','	50/34 Le Dai Hanh, Q10, TpHCM','	0853322233','	leduc@gmail.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1138','	Tran Van Binh','	284 ?o Xuan Hop, Q 9, TpHCM','	0989677543','	tranbinh@gmai.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1240','	Ngo Thi Hong Anh','	93 Man Thien, Q9, TpHCM','	0855147311',	'ngoanh@gmail.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1329',	'Lam Thi Hong','	 2A Binh Chieu, Q. Thu Duc, TpHCM','	0989057777','	lamhong@gmail.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1275','	Le Van Minh','	34 Thong Nhat, Q. Thu Duc, TpHCM','	0362131481','	leminh@gmail.com');
INSERT INTO CUSTOMER (CUSID,CUSNAME, CUSADD, CUSMOBILE, CUSEMAIL) VALUES('KH1377','	Tran Thi Mo','	123 Thanh Loc, Q.12, TpHCM','	0909023498','	tranmo@gmail.com');