-- tao bang ORDERDETAILS_IM
CREATE TABLE ORDERDETAILS_IM (
    ORD_IM_NUM VARCHAR2(10) NOT NULL,
    REID VARCHAR2(10) NOT NULL,
    QUANTITY NUMBER(7)
); 
--Tao khoa ngoai
ALTER TABLE ORDERDETAILS_IM
add CONSTRAINT FK_ORDERDETAILS_IM_RESOURCES FOREIGN KEY (REID) REFERENCES RESOURCES(REID);

ALTER TABLE ORDERDETAILS_IM
add CONSTRAINT FK_ORDERDETAILS_IM_ORDER_IMPORT FOREIGN KEY (ORD_IM_NUM) REFERENCES ORDER_IMPORT(ORD_IM_NUM);

ALTER TABLE ORDERDETAILS_IM
add CONSTRAINT ORDERDETAILS_IM_PK PRIMARY KEY (ORD_IM_NUM, REID);
--INSERT
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM452','RE001',120);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM435','RE003',78);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM535','RE001',120);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM578','RE003',67);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM601','RE004',78);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM623','RE002',157);
INSERT INTO ORDERDETAILS_IM (ORD_IM_NUM, REID, QUANTITY) VALUES ('IM630','RE005',140);
