--. tao bang ORDERDETAILS_EX
CREATE TABLE ORDERDETAILS_EX (
    ORD_EX_NUM VARCHAR2(10) NOT NULL,
    PROID             VARCHAR2(10) NOT NULL,
    QUANTITY       NUMBER(7)
); 
--Tao khoa ngoai
ALTER TABLE ORDERDETAILS_EX
add CONSTRAINT FK_ORDERDETAILS_EX_ORDER_EXPORT FOREIGN KEY (ORD_EX_NUM) REFERENCES ORDER_EXPORT(ORD_EX_NUM);

ALTER TABLE ORDERDETAILS_EX
add CONSTRAINT FK_ORDERDETAILS_EX_ORDER_PRODUCT FOREIGN KEY (PROID) REFERENCES PRODUCT(PROID);

ALTER TABLE ORDERDETAILS_EX
add CONSTRAINT ORDERDETAILS_EX_PK PRIMARY KEY (ORD_EX_NUM, PROID);
--INSERT
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1252','P023',15);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1252','P013',20);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1278','P032',30);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1278','P013',30);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1278','P014',30);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1307','P028',20);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1322','P017',5);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1322','P007',10);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1322','P021',15);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1414','P016',30);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1414','P013',40);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1429','P026',25);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1429','P023',30);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1690','P021',50);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1601','P032',20);
INSERT INTO ORDERDETAILS_EX (ORD_EX_NUM, PROID, QUANTITY) VALUES ('EX1645','P028',17);


