--tao bang PRODUCT 
CREATE TABLE PRODUCT (
    PROID            VARCHAR2(10) NOT NULL,
    PRONAME      VARCHAR2(20),
    PROPRICE     NUMBER(11,2),
    FARMID         VARCHAR2(10),
    INVENTORY   NUMBER(7),
    STOCKID       VARCHAR2(10),
    PRIMARY KEY (PROID)
); 
--tao Khoa ngoai

ALTER TABLE PRODUCT
add CONSTRAINT FK_PRODUCT_FARM FOREIGN KEY (FARMID) REFERENCES FARM(FARMID);

ALTER TABLE PRODUCT
add CONSTRAINT FK_PRODUCT_STOCK FOREIGN KEY (STOCKID) REFERENCES STOCK(STOCKID);
--INSSERT
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P013', 'Ca rot', 11000, '1', '120', 'S1');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P014', 'Dua leo', 13000, '1', '115', 'S1');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P016', 'Khoai tay', 12000, '2', '170', 'S3');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P023', 'Cai bo xoi', 23000, '3', '212', 'S5');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P007', 'Dau bap', 18000, '2', '135', 'S3');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P026', 'Bi do', 9000, '2', '97', 'S3');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P021', 'Cai ngot', 9000, '3', '143', 'S5');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P032', 'Bap non', 30000, '4', '167', 'S7');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P017', 'Kho qua', 14000, '4', '127', 'S7');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P028', 'Ca chua', 24000, '1', '88', 'S1');
INSERT INTO PRODUCT (PROID, PRONAME, PROPRICE, FARMID, INVENTORY, STOCKID) VALUES ('P013', 'Ca rot', 11000, '1', '120', 'S1');
