-- tao bang SUPPLIER 
CREATE TABLE SUPPLIER (
    SUPID           VARCHAR2(10) NOT NULL,
    SUPNAME     VARCHAR2(50) NOT NULL,
    SUPADD       VARCHAR2(400),
    SUPMOBILE  VARCHAR2(25),
    SUPEMAIL     VARCHAR2(100),
    PRIMARY KEY (SUPID)
); 
--INSERT
INSERT INTO SUPPLIER (SUPID, SUPNAME, SUPADD, SUPMOBILE, SUPEMAIL) VALUES ('SU001', 'CTY VINH HUNG', ' 43 M?c ??nh Chi, Ph??ng ?a Kao, Qu?n 1, TP. HCM', '028 3825 6258', 'info@vinhhung.com');
INSERT INTO SUPPLIER (SUPID, SUPNAME, SUPADD, SUPMOBILE, SUPEMAIL) VALUES ('SU002', 'CTY PHU MY', ' C12/21 Tân Kiên, Qu?n Bình Chánh, TP. HCM', ' 0292 3841 304', 'info@phumy.com');
INSERT INTO SUPPLIER (SUPID, SUPNAME, SUPADD, SUPMOBILE, SUPEMAIL) VALUES ('SU003', 'CTY PHAN BON CAN THO', ' Khu Công nghi?p Trà Nóc 1, Trà Nóc, Bình Thu?, TP. C?n Th?, C?n Th?', ' 0292 3841 043', 'info@cfccobay.com')
INSERT INTO SUPPLIER (SUPID, SUPNAME, SUPADD, SUPMOBILE, SUPEMAIL) VALUES ('SU004', 'CTY SEN VANG', ' 210 Ph?m Công Tr?, KDC 143ha, Th?nh M? L?i, Qu?n 2, TP. H? Chí Minh', '093 8123494', 'sales@senvang.com');
INSERT INTO SUPPLIER (SUPID, SUPNAME, SUPADD, SUPMOBILE, SUPEMAIL) VALUES ('SU005', 'CTY BINH MINH', '53A, ???ng 77, Tân Quy, Qu?n 7, TP. H? Chí Minh', '0913 723 236', 'cskh@binhminh.com');
