/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author DoQuynhChi
 */
public class JNode extends javax.swing.JPanel {
    private static int counter = 0;

    /**
     * Creates new form JNode
     */
    public JNode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTenSP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHinh = new javax.swing.JLabel();
        jLabelSoLuong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jButtonGiam = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 184, 77));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(234, 266));

        jLabelTenSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTenSP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTenSP.setText("Vải");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Số lượng:");

        jLabelHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/vai.jpg"))); // NOI18N

        jLabelSoLuong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Giá:");

        jLabelGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGia.setPreferredSize(new java.awt.Dimension(17, 17));

        jButtonGiam.setBackground(new java.awt.Color(46, 184, 184));
        jButtonGiam.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonGiam.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGiam.setText("-");
        jButtonGiam.setAlignmentY(0.0F);
        jButtonGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiamActionPerformed(evt);
            }
        });

        jButtonThem.setBackground(new java.awt.Color(46, 184, 184));
        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThem.setText("+");
        jButtonThem.setAlignmentY(0.0F);
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelGia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jButtonGiam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonThem))
                            .addComponent(jLabelTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelHinh)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelHinh)
                .addGap(18, 18, 18)
                .addComponent(jLabelTenSP)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGiam)
                            .addComponent(jButtonThem))))
                .addContainerGap())
        );

        jButtonGiam.getAccessibleContext().setAccessibleName("-");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGiamActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThemActionPerformed

    public JButton getjButtonThem() {
        return jButtonThem;
    }

    public void setjButtonThem(JButton jButtonThem) {
        this.jButtonThem = jButtonThem;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabelGia() {
        return jLabelGia;
    }

    public void setjLabelGia(JLabel jLabelGia) {
        this.jLabelGia = jLabelGia;
    }

    public JLabel getjLabelHinh() {
        return jLabelHinh;
    }

    public void setjLabelHinh(JLabel jLabelHinh) {
        this.jLabelHinh = jLabelHinh;
    }

    public JLabel getjLabelSoLuong() {
        return jLabelSoLuong;
    }

    public void setjLabelSoLuong(JLabel jLabelSoLuong) {
        this.jLabelSoLuong = jLabelSoLuong;
    }

    public JLabel getjLabelTenSP() {
        return jLabelTenSP;
    }

    public void setjLabelTenSP(JLabel jLabelTenSP) {
        this.jLabelTenSP = jLabelTenSP;
    }



    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGiam;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelHinh;
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenSP;
    // End of variables declaration//GEN-END:variables
}
