/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Order_Details_Ex;
import Model.Order_Export;
import Model.Product;
import Process.C_NewOrderExport;
import Process.C_Order_Details_Ex;
import Process.C_Product;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author DoQuynhChi
 */
public class NewOrderExport extends javax.swing.JFrame {
    private ArrayList<String> arrLDisCode = new ArrayList<>();
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
    String ngayHD = LocalDate.now().format(dtf);
    LocalDate ld = LocalDate.parse(ngayHD, dtf);
    Date dateOrder = Date.valueOf(ld);
    
    double totalOrder = 0;
    String shipCode;
    String codeDiscount;
    String[] info_kh = new String[3];
    boolean tonTai;
    
    
    
    /**
     * Creates new form NewOrderExport
     */
    public NewOrderExport(long tongTien) {
        initComponents();
         this.setLocationRelativeTo(null);
         
        totalOrder = tongTien;
        jLabelNgayHD.setText(ngayHD);
        jLabelTongTien.setText(String.valueOf(tongTien));
        jLabelThanhTien.setText(String.valueOf(tongTien));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonThanhToan = new javax.swing.JButton();
        txtFTenKH = new javax.swing.JTextField();
        txtFSdtKH = new javax.swing.JTextField();
        txtFDiaChi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxMaKM = new javax.swing.JComboBox<>();
        jLabelTongTien = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();
        jLabelNgayHD = new javax.swing.JLabel();
        jCheckBoxKHTV = new javax.swing.JCheckBox();
        jCheckBoxVanChuyen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("HÓA ĐƠN MUA HÀNG");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Ngày lập hóa đơn:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Số điện thoại:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Họ tên khách hàng:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Mã giảm giá:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setText("Thành tiền:");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/return.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonThanhToan.setBackground(new java.awt.Color(102, 255, 153));
        jButtonThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/payment.png"))); // NOI18N
        jButtonThanhToan.setText("Ðã thanh toán");
        jButtonThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThanhToanActionPerformed(evt);
            }
        });

        txtFTenKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txtFSdtKH.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtFSdtKH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtFSdtKHMouseMoved(evt);
            }
        });
        txtFSdtKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFSdtKHFocusLost(evt);
            }
        });
        txtFSdtKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFSdtKHActionPerformed(evt);
            }
        });
        txtFSdtKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFSdtKHKeyPressed(evt);
            }
        });

        txtFDiaChi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtFDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFDiaChiActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/invoice.png"))); // NOI18N

        jComboBoxMaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaKMActionPerformed(evt);
            }
        });

        jLabelTongTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabelThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabelNgayHD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jCheckBoxKHTV.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxKHTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxKHTV.setText("Khách hàng thành viên");
        jCheckBoxKHTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxKHTVActionPerformed(evt);
            }
        });

        jCheckBoxVanChuyen.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxVanChuyen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBoxVanChuyen.setText("Vận chuyển");
        jCheckBoxVanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVanChuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBoxKHTV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                        .addComponent(txtFSdtKH, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFTenKH, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelThanhTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonThanhToan))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabelNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jCheckBoxKHTV)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFSdtKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxVanChuyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDiaChiActionPerformed

    private void jButtonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThanhToanActionPerformed
        String disID;

        if (tonTai) { // Neu khach hang da co trong he thong
            try {
                // them hoa don vao co so du lieu
                disID = C_NewOrderExport.layDisID(codeDiscount);
                double preTotal = 0;
                double total = 0;
                
                //

                Order_Export newOrder = new Order_Export(dateOrder, info_kh[0], preTotal, disID, total, shipCode);

                // them hoa don moi vao co so du lieu
                String maHD = C_NewOrderExport.themOrderExport(newOrder);

                ArrayList<Product> arrLProPurchase = ChooseProductPage.luuThongTinCTHD();

                // them danh sach chon mua vao bang CTHD
                for (int v = 0; v < arrLProPurchase.size(); v++) {
                    String tenSP = arrLProPurchase.get(v).getProName();
                    String maSP;
                    try {
                        maSP = C_Product.getProID(tenSP);
                        int soLuong = arrLProPurchase.get(v).getQuantity();

                        Order_Details_Ex newCTHD = new Order_Details_Ex(maHD, maSP, soLuong);
                        C_Order_Details_Ex.themCTHD(newCTHD);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

                //in thong bao them thanh cong
                JOptionPane.showMessageDialog(this, "Đơn hàng đã được ghi nhận");
                
            } catch (SQLException ex) {
                Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else {  // Them khach hang moi
            try {
                disID = null;
                double preTotal = 0;
                double total = 0;
                
                //kiem tra thong tin ho ten va so dien thoai khach hang khong duoc de trong
                if (txtFTenKH.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Nhập họ tên và số điện thoại khách hàng là bắt buộc!");
                } 
                else {
                    String maKH = C_NewOrderExport.layMaKH(txtFTenKH.getText(), txtFSdtKH.getText());

                    Order_Export newOrder = new Order_Export(dateOrder, maKH, preTotal, disID, total, shipCode);

                    // them hoa don moi vao co so du lieu
                    String maHD = C_NewOrderExport.themOrderExport(newOrder);

                    ArrayList<Product> arrLProPurchase = ChooseProductPage.luuThongTinCTHD();

                    // them danh sach chon mua vao bang CTHD
                    for (int v = 0; v < arrLProPurchase.size(); v++) {
                        String tenSP = arrLProPurchase.get(v).getProName();
                        String maSP;
                        try {
                            maSP = C_Product.getProID(tenSP);
                            int soLuong = arrLProPurchase.get(v).getQuantity();

                            Order_Details_Ex newCTHD = new Order_Details_Ex(maHD, maSP, soLuong);
                            C_Order_Details_Ex.themCTHD(newCTHD);
                            
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                    
                       //in thong bao them thanh cong
                            JOptionPane.showMessageDialog(this, "Đơn hàng đã được ghi nhận");
                }

            } catch (SQLException ex) {
                Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonThanhToanActionPerformed

    private void txtFSdtKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFSdtKHActionPerformed

    }//GEN-LAST:event_txtFSdtKHActionPerformed

    private void txtFSdtKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFSdtKHKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFSdtKHKeyPressed

    private void txtFSdtKHMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFSdtKHMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFSdtKHMouseMoved

    private void txtFSdtKHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFSdtKHFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFSdtKHFocusLost

    private void show_Combobox_DisCode(String sdt, LocalDate dateOrder) throws SQLException, ClassNotFoundException {
        
        arrLDisCode = C_NewOrderExport.getDisCode(sdt, dateOrder);
        
        // Lay code khuyen mai dua tren loai khach hang va ngay mua hang, load vao combobox
        for (String id : arrLDisCode) {
                jComboBoxMaKM.addItem(id);
        }
    }
    
    private void jComboBoxMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaKMActionPerformed
        // TODO add your handling code here:
        int index = jComboBoxMaKM.getSelectedIndex();
        codeDiscount = arrLDisCode.get(index);
        
        double triGia = 0;
        try {
            triGia = C_NewOrderExport.timGiaTriKhuyenMai(codeDiscount);
        } catch (SQLException ex) {
            Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Hien thi thanh tien sau cung khi chon ma khuyen mai
        double thanhTien = totalOrder * (1 -  triGia);
        jLabelThanhTien.setText(String.valueOf(thanhTien));
    }//GEN-LAST:event_jComboBoxMaKMActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPanel1.requestFocus(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jCheckBoxKHTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxKHTVActionPerformed
        // TODO add your handling code here:
        txtFTenKH.setEditable(false);
        txtFDiaChi.setEditable(false);

        txtFSdtKH.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent evt) {
                String sdt = txtFSdtKH.getText();

                try {
                    info_kh = C_NewOrderExport.timKH(sdt);

                } catch (SQLException ex) {
                    int code = ex.getErrorCode();
                    String msg = ex.getMessage();
                    JOptionPane.showMessageDialog(null, msg, String.valueOf(code), JOptionPane.ERROR_MESSAGE);   
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
                }
                

                if (info_kh[1] == null || info_kh[2] == null) {
                    txtFTenKH.setEditable(true);
                    txtFDiaChi.setEditable(true);
                } else {
                    txtFTenKH.setText(info_kh[1]);
                    txtFDiaChi.setText(info_kh[2]);
                    txtFTenKH.setEditable(false);
                    txtFDiaChi.setEditable(false);
                    txtFSdtKH.setEditable(false);
                    tonTai = true;
                }

                try {
                    show_Combobox_DisCode(sdt, LocalDate.now());
                } catch (SQLException ex) {
                    Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void focusGained(FocusEvent e) {

            }

        });
    }//GEN-LAST:event_jCheckBoxKHTVActionPerformed

    private void jCheckBoxVanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVanChuyenActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            shipCode = C_NewOrderExport.taoMaVanChuyen();
        } catch (SQLException ex) {
            Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewOrderExport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCheckBoxVanChuyenActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonThanhToan;
    private javax.swing.JCheckBox jCheckBoxKHTV;
    private javax.swing.JCheckBox jCheckBoxVanChuyen;
    private javax.swing.JComboBox<String> jComboBoxMaKM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNgayHD;
    private javax.swing.JLabel jLabelThanhTien;
    private javax.swing.JLabel jLabelTongTien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFDiaChi;
    private javax.swing.JTextField txtFSdtKH;
    private javax.swing.JTextField txtFTenKH;
    // End of variables declaration//GEN-END:variables
}
