/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Feedback_M;
import Process.Feedback_C;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author pem41
 */
public class Feedback extends javax.swing.JFrame {

    /**
     * Creates new form Feedback
     */
    String id_login;
    public Feedback(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        id_login = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnsendFeedback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        iconAnh = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jlabel4 = new javax.swing.JLabel();
        txtnameCus = new javax.swing.JTextField();
        jabel7 = new javax.swing.JLabel();
        txtemailCus = new javax.swing.JTextField();
        btn_themAnh = new javax.swing.JButton();
        textLinkanh = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Đánh giá & Phản hồi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, -1, -1));

        btnsendFeedback.setBackground(new java.awt.Color(244, 211, 94));
        btnsendFeedback.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsendFeedback.setForeground(new java.awt.Color(51, 51, 51));
        btnsendFeedback.setText("Gửi");
        btnsendFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendFeedbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnsendFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Hãy cho chúng tôi biết trải nghiệm của bạn:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        iconAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/image.png"))); // NOI18N
        iconAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAnhMouseClicked(evt);
            }
        });
        jPanel1.add(iconAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 387, -1, -1));
        jPanel1.add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 234, 543, 135));

        jlabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabel4.setText("Họ tên:");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, -1));

        txtnameCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameCusActionPerformed(evt);
            }
        });
        jPanel1.add(txtnameCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 93, 199, 32));

        jabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jabel7.setText("Email");
        jPanel1.add(jabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 98, -1, -1));

        txtemailCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailCusActionPerformed(evt);
            }
        });
        jPanel1.add(txtemailCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 94, 230, 30));

        btn_themAnh.setText("Đính kèm ảnh");
        btn_themAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themAnhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_themAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 389, -1, -1));
        jPanel1.add(textLinkanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 320, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/return.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameCusActionPerformed

    private void txtemailCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailCusActionPerformed

    private void btnsendFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendFeedbackActionPerformed
         boolean check = false;
         String textnameCus= txtnameCus.getText();
        String textemailCus = txtemailCus.getText();
        String textmessage = txtMessage.getText();
        String fb_image= textLinkanh.getText();
        DateTimeFormatter dtf =  DateTimeFormatter.ofPattern("dd-MMM-yy");
        String ngaytao = LocalDate.now().format(dtf);
        LocalDate ld = LocalDate.parse(ngaytao, dtf);
        Date datesend = Date.valueOf(ld);
        try {

            Feedback_M fb = new Feedback_M("", textnameCus, textemailCus, textmessage, fb_image, datesend);
            check = Feedback_C.insertFeedback(fb);
            if (check != true) {
                JOptionPane.showMessageDialog(this, "Gửi thất bại, vui lòng kiểm tra lại!",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Cảm ơn bạn đã đóng góp ý kiến!");
            }
        } catch (SQLException ex) {
            int code = ex.getErrorCode();
            String msg = ex.getMessage();
            JOptionPane.showMessageDialog(this, msg, String.valueOf(code), JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Feedback.class.getName()).log(Level.SEVERE, null, ex);
        }


            
         
    }//GEN-LAST:event_btnsendFeedbackActionPerformed

    private void iconAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAnhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconAnhMouseClicked

    private void btn_themAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themAnhActionPerformed
      try {
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Hình", "jpg", "png", "jpeg");
            fileChooser.setFileFilter(imageFilter);
            fileChooser.setMultiSelectionEnabled(false);
            int x = fileChooser.showDialog(this, "Chọn file");
            if (x == JFileChooser.APPROVE_OPTION) {
                File file_in = fileChooser.getSelectedFile();
                String path = file_in.getAbsolutePath();

                File inStream = new File(path);

                File file_out = new File("");
                textLinkanh.setText(inStream.getName());
                File outStream = new File(file_out.getAbsolutePath() + "/src/Resources/" + inStream.getName());

                Files.copy(inStream.toPath(), outStream.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
                     
    }//GEN-LAST:event_btn_themAnhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KH_Introduction1(id_login).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themAnh;
    private javax.swing.JButton btnsendFeedback;
    private javax.swing.JLabel iconAnh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jabel7;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JTextField textLinkanh;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtemailCus;
    private javax.swing.JTextField txtnameCus;
    // End of variables declaration//GEN-END:variables
}