/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author doquy
 */
public class JFoodCard extends javax.swing.JPanel {

    /**
     * Creates new form JFoodCard
     */
    public JFoodCard() {
        initComponents();
        jTextAreaCongThuc.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCongThuc = new javax.swing.JTextArea();
        jLabelTenMon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaCongThuc.setColumns(20);
        jTextAreaCongThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaCongThuc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCongThuc);

        jLabelTenMon.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTenMon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelHinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelHinh() {
        return jLabelHinh;
    }

    public void setjLabelHinh(JLabel jLabelHinh) {
        this.jLabelHinh = jLabelHinh;
    }

    public JTextArea getjTextAreaCongThuc() {
        return jTextAreaCongThuc;
    }

    public void setjTextAreaCongThuc(JTextArea jTextAreaCongThuc) {
        this.jTextAreaCongThuc = jTextAreaCongThuc;
    }

    public JLabel getjLabelTenMon() {
        return jLabelTenMon;
    }

    public void setjLabelTenMon(JLabel jLabelTenMon) {
        this.jLabelTenMon = jLabelTenMon;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHinh;
    private javax.swing.JLabel jLabelTenMon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCongThuc;
    // End of variables declaration//GEN-END:variables
}
