--. tao bang EMPLOYEE 
CREATE TABLE EMPLOYEE (
    EMPID VARCHAR2(10) NOT NULL,
    FARMID VARCHAR2(10) NOT NULL,
    EMPNAME VARCHAR2(40) NOT NULL,
    EMPPHONE VARCHAR(25),
    EMPADD VARCHAR2(400),
    EMPEMAIL VARCHAR2(50), 
    PRIMARY KEY (EMPID)
); 
--tao khoa ngoai
ALTER TABLE EMPLOYEE
add CONSTRAINT FK_EMPLOYEE_FARM FOREIGN KEY (FARMID) REFERENCES FARM(FARMID);
--INSERT
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV11', '1', 'Nguyen Duc Tai', '0989143388', '300/47 Nguyen Van Linh, Q7, TpHCM', 'nguyentai@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV12', '3', 'Tran Thi Thom', '0902544722', '34/5 Pham Van Chieu, Q. Go Vap, TpHCM', 'tranthom@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV13', '1', 'Le Minh Hai', '0909876561', '414/16 Dien Bien Phu, Q10, TpHCM', 'lehai@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV14', '2', 'Nguyen Khanh Toan', '0337127332', '3/5 Nguyen Van Thu, Q1, TpHCM', 'nguyentoan@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV15', '2', 'Nguyen Thi Lieu', '0789578316', '44 Linh Trung, Q. Thu Duc, TpHCM', 'nguyenlieu@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV16', '4', 'Tran Trung Kien', '0283619981', '54 Xuan Dieu, Q. Tan Binh, TpHCM', 'trankien@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV17', '3', 'Le Thi Huong', '0909242935', '13 Phan Van Tri, Q. Go Vap, TpHCM', 'lehuong@gmail.com');
INSERT INTO EMPLOYEE (EMPID, FARMID, EMPNAME, EMPPHONE,EMPADD, EMPEMAIL) VALUES  ('NV18', '4', 'Nguyen Van Linh', '0978655893', '80/2A Huynh Van Nghe, Q.Tan Binh, TpHCM', 'nguyenlinh@gmail.com');





