-- tao bang RESOURCES 
CREATE TABLE RESOURCES (
    REID VARCHAR2(10) NOT NULL,
    RESNAME VARCHAR2(50) NOT NULL,
    STOCKID VARCHAR2(10),
    PRIMARY KEY (REID)
 
); 
--Tao khoa ngoai
ALTER TABLE RESOURCES
add CONSTRAINT FK_RESOURCES_STOCK FOREIGN KEY (STOCKID) REFERENCES STOCK(STOCKID);
--INSERT
INSERT INTO RESOURCES (REID, RESNAME, STOCKID) VALUES ('RE001', 'Phan bon', 'S2');
INSERT INTO RESOURCES (REID, RESNAME, STOCKID) VALUES ('RE002', 'Hat giong', 'S4');
INSERT INTO RESOURCES (REID, RESNAME, STOCKID) VALUES ('RE003', 'Thuoc bao ve thuc vat', 'S6');
INSERT INTO RESOURCES (REID, RESNAME, STOCKID) VALUES ('RE004', 'Chat cai tao moi truong', 'S8');
INSERT INTO RESOURCES (REID, RESNAME, STOCKID) VALUES ('RE005', 'Dat trong', 'S2');