--. tao bang STOCK
CREATE TABLE STOCK (
    STOCKID             VARCHAR2(10) NOT NULL,
    STATUSSTOCK   NUMBER(7),
    OVERDUE            NUMBER(7),
    "TYPE"                  NUMBER(7),
    PRIMARY KEY (STOCKID)
); 
--INSERT
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S1',1,	7,	1);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S2',1,null,0);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S3',0,11,1);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S4',1,null,0);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S5',1,9,1);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S6',1,null,0);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S7',1,13,1);
INSERT INTO STOCK (STOCKID, STATUSSTOCK, OVERDUE, TYPE) VALUES ('S8',1,null,0);