CREATE TABLE TRANSPORT  (
    TRANSID VARCHAR2(10) NOT NULL,
    ORD_EX_NUM VARCHAR2(10) NOT NULL,
    STATUSTRANS INT,
    primary key (TRANSID)
); 
ALTER TABLE TRANSPORT
add CONSTRAINT FK_TRANSPORT_ORDER_EXPORT FOREIGN KEY (ORD_EX_NUM) REFERENCES ORDER_EXPORT(ORD_EX_NUM);
----INSERT
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR524', 'EX1252', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR525', 'EX1278', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR530', 'EX1307', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR532', 'EX1322', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR545', 'EX1414', 0);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR547', 'EX1429', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR564', 'EX1690', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR558', 'EX1601', 1);
INSERT INTO TRANSPORT (TRANSID, ORD_EX_NUM, STATUSTRANS) VALUES ('TR560', 'EX1645', 0);
