package GUI;


import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author diuai
 */
public class AdminHome extends javax.swing.JFrame {
    /**
     * Creates new form AdminHome
     */
    CardLayout cardlayout;

    public AdminHome() {
        initComponents();
         cardlayout=(CardLayout)jpnCardLayout.getLayout();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtManaPro = new javax.swing.JButton();
        jbtManaFarm = new javax.swing.JButton();
        jbtManaOrder = new javax.swing.JButton();
        jbtManaRe = new javax.swing.JButton();
        jbtManaSup = new javax.swing.JButton();
        jbtManaCus = new javax.swing.JButton();
        jbtManaDis = new javax.swing.JButton();
        jbtManaStock = new javax.swing.JButton();
        jbtManaEmp = new javax.swing.JButton();
        jbtManaTrans = new javax.swing.JButton();
        jbtManaStatis = new javax.swing.JButton();
        jpnCardLayout = new javax.swing.JPanel();
        jpnCard1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnthemSP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnxoaSP = new javax.swing.JButton();
        btnsuaSP = new javax.swing.JButton();
        jpnCard2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnthemNongTrai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnxoaNongTrai = new javax.swing.JButton();
        btnsuaNongTrai = new javax.swing.JButton();
        jpnCard3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jpnCard4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnthemVL = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btnxoaVL = new javax.swing.JButton();
        btnsuaVL = new javax.swing.JButton();
        jpnCard5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnthemNCC = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnxoaNCC = new javax.swing.JButton();
        btnsuaNCC = new javax.swing.JButton();
        jpnCard6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        btnthemKH = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        btnxoaKH = new javax.swing.JButton();
        btnsuaKH = new javax.swing.JButton();
        jpnCard7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        btnthemMaKM = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btnxoaMaKM = new javax.swing.JButton();
        btnsuaMaKM = new javax.swing.JButton();
        jpnCard8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btnthemKho = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        btnxoaKho = new javax.swing.JButton();
        btnsuaKho = new javax.swing.JButton();
        jpnCard9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jpnCard10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jpnCard11 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton9.setText("jButton9");

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 179, 179));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FRESHFOOD");

        jbtManaPro.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaPro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaPro.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\vegetable.png")); // NOI18N
        jbtManaPro.setText("QUẢN LÝ NÔNG SẢN");
        jbtManaPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtManaPro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaProActionPerformed(evt);
            }
        });

        jbtManaFarm.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaFarm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaFarm.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\farm.png")); // NOI18N
        jbtManaFarm.setText("QUẢN LÝ TRANG TRẠI");
        jbtManaFarm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaFarmActionPerformed(evt);
            }
        });

        jbtManaOrder.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\order (1).png")); // NOI18N
        jbtManaOrder.setText("QUẢN LÝ BÁN HÀNG");
        jbtManaOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaOrderActionPerformed(evt);
            }
        });

        jbtManaRe.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaRe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaRe.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\fertilizer.png")); // NOI18N
        jbtManaRe.setText("QUẢN LÝ NGUYÊN VẬT LIỆU");
        jbtManaRe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaReActionPerformed(evt);
            }
        });

        jbtManaSup.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaSup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaSup.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\supplier.png")); // NOI18N
        jbtManaSup.setText("QUẢN LÝ NHÀ CUNG CẤP");
        jbtManaSup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaSupActionPerformed(evt);
            }
        });

        jbtManaCus.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaCus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaCus.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\customer.png")); // NOI18N
        jbtManaCus.setText("QUẢN LÝ KHÁCH HÀNG");
        jbtManaCus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaCusActionPerformed(evt);
            }
        });

        jbtManaDis.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaDis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaDis.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\gift-voucher.png")); // NOI18N
        jbtManaDis.setText("QUẢN LÝ MÃ KHUYẾN MÃI");
        jbtManaDis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaDisActionPerformed(evt);
            }
        });

        jbtManaStock.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaStock.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\warehouse.png")); // NOI18N
        jbtManaStock.setText("QUẢN LÝ KHO");
        jbtManaStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaStockActionPerformed(evt);
            }
        });

        jbtManaEmp.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaEmp.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\employee.png")); // NOI18N
        jbtManaEmp.setText("QUẢN LÝ NHÂN VIÊN");
        jbtManaEmp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaEmpActionPerformed(evt);
            }
        });

        jbtManaTrans.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaTrans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaTrans.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\shipment.png")); // NOI18N
        jbtManaTrans.setText("QUẢN LÝ VẬN CHUYỂN");
        jbtManaTrans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaTransActionPerformed(evt);
            }
        });

        jbtManaStatis.setBackground(new java.awt.Color(244, 211, 94));
        jbtManaStatis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtManaStatis.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\analysis.png")); // NOI18N
        jbtManaStatis.setText("THỐNG KÊ");
        jbtManaStatis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtManaStatis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtManaStatisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtManaPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaFarm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaCus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtManaStatis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaFarm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaRe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaSup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaCus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtManaStatis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jpnCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        jpnCardLayout.setLayout(new java.awt.CardLayout());

        jpnCard1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DANH SÁCH SẢN PHẨM");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnthemSP.setBackground(new java.awt.Color(244, 211, 94));
        btnthemSP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnthemSP.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemSP.setText("Thêm sản phẩm");

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Mã sản phẩm", "Tên sản phẩm", "Loại", "Có thể bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaSP.setBackground(new java.awt.Color(244, 211, 94));
        btnxoaSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaSP.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaSP.setText("Xóa");

        btnsuaSP.setBackground(new java.awt.Color(244, 211, 94));
        btnsuaSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaSP.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaSP.setText("Sửa");

        javax.swing.GroupLayout jpnCard1Layout = new javax.swing.GroupLayout(jpnCard1);
        jpnCard1.setLayout(jpnCard1Layout);
        jpnCard1Layout.setHorizontalGroup(
            jpnCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemSP))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jpnCard1Layout.setVerticalGroup(
            jpnCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpnCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnthemSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard1, "jpnListPro");

        jpnCard2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DANH SÁCH NÔNG TRẠI");

        btnthemNongTrai.setBackground(new java.awt.Color(244, 211, 94));
        btnthemNongTrai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemNongTrai.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemNongTrai.setText("Thêm nông trại");
        btnthemNongTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemNongTraiActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Mã nông trại", "Tên nông trại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaNongTrai.setBackground(new java.awt.Color(244, 211, 94));
        btnxoaNongTrai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaNongTrai.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaNongTrai.setText("Xóa");
        btnxoaNongTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaNongTraiActionPerformed(evt);
            }
        });

        btnsuaNongTrai.setBackground(new java.awt.Color(244, 211, 94));
        btnsuaNongTrai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaNongTrai.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/diuai/Downloads/pencil.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnsuaNongTrai.setText("Sửa");

        javax.swing.GroupLayout jpnCard2Layout = new javax.swing.GroupLayout(jpnCard2);
        jpnCard2.setLayout(jpnCard2Layout);
        jpnCard2Layout.setHorizontalGroup(
            jpnCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaNongTrai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaNongTrai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemNongTrai))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jpnCard2Layout.setVerticalGroup(
            jpnCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jpnCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemNongTrai)
                    .addComponent(btnxoaNongTrai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuaNongTrai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(569, 569, 569))
        );

        jpnCardLayout.add(jpnCard2, "jpnListFarm");

        jpnCard3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DANH SÁCH ĐƠN HÀNG");

        jButton20.setBackground(new java.awt.Color(244, 211, 94));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        jButton20.setText("Tạo đơn mới");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Mã đơn hàng", "Mã khách hàng", "Ngày tạo", "Mã vận chuyển", "Tổng tiền", "Mã giảm giá", "Thành tiền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        javax.swing.GroupLayout jpnCard3Layout = new javax.swing.GroupLayout(jpnCard3);
        jpnCard3.setLayout(jpnCard3Layout);
        jpnCard3Layout.setHorizontalGroup(
            jpnCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jpnCard3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCard3Layout.setVerticalGroup(
            jpnCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jpnCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard3, "jpnListOrder");

        jpnCard4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DANH SÁCH NGUYÊN VẬT LIỆU");

        btnthemVL.setBackground(new java.awt.Color(244, 211, 94));
        btnthemVL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemVL.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemVL.setText("Thêm nguyên vật liệu");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Mã nguyên vật liệu", "Tên nguyên vật liệu", "Giá", "Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaVL.setBackground(new java.awt.Color(248, 211, 94));
        btnxoaVL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaVL.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaVL.setText("Xóa");
        btnxoaVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaVLActionPerformed(evt);
            }
        });

        btnsuaVL.setBackground(new java.awt.Color(248, 211, 94));
        btnsuaVL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaVL.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaVL.setText("Sửa");

        javax.swing.GroupLayout jpnCard4Layout = new javax.swing.GroupLayout(jpnCard4);
        jpnCard4.setLayout(jpnCard4Layout);
        jpnCard4Layout.setHorizontalGroup(
            jpnCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard4Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemVL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCard4Layout.setVerticalGroup(
            jpnCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthemVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );

        jpnCardLayout.add(jpnCard4, "jpnListRe");

        jpnCard5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DANH SÁCH NHÀ CUNG CẤP");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btnthemNCC.setBackground(new java.awt.Color(244, 211, 94));
        btnthemNCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemNCC.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemNCC.setText("Thêm nhà cung cấp");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Địa chỉ", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaNCC.setBackground(new java.awt.Color(248, 211, 94));
        btnxoaNCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaNCC.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaNCC.setText("Xóa");
        btnxoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaNCCActionPerformed(evt);
            }
        });

        btnsuaNCC.setBackground(new java.awt.Color(248, 211, 94));
        btnsuaNCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaNCC.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaNCC.setText("Sửa");
        btnsuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnCard5Layout = new javax.swing.GroupLayout(jpnCard5);
        jpnCard5.setLayout(jpnCard5Layout);
        jpnCard5Layout.setHorizontalGroup(
            jpnCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard5Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaNCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaNCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemNCC))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jpnCard5Layout.setVerticalGroup(
            jpnCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthemNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(btnxoaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard5, "jpnListSup");

        jpnCard6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(0, 179, 179));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DANH SÁCH KHÁCH HÀNG");

        btnthemKH.setBackground(new java.awt.Color(244, 211, 94));
        btnthemKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemKH.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemKH.setText("Thêm khách hàng");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Mã khách hàng", "Tên khách hàng", "Giới tính", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Email", "Loại", "Acc_money"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaKH.setBackground(new java.awt.Color(248, 211, 94));
        btnxoaKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaKH.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaKH.setText("Xóa");

        btnsuaKH.setBackground(new java.awt.Color(248, 211, 94));
        btnsuaKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaKH.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaKH.setText("Sửa");

        javax.swing.GroupLayout jpnCard6Layout = new javax.swing.GroupLayout(jpnCard6);
        jpnCard6.setLayout(jpnCard6Layout);
        jpnCard6Layout.setHorizontalGroup(
            jpnCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCard6Layout.setVerticalGroup(
            jpnCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthemKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard6, "jpnListCus");

        jpnCard7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("QUẢN LÍ MÃ KHUYẾN MÃI");

        btnthemMaKM.setBackground(new java.awt.Color(244, 211, 94));
        btnthemMaKM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemMaKM.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemMaKM.setText("Thêm mã khuyến mãi");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Mã khuyến mãi", "Mã code", "Giá trị", "Loại", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaMaKM.setBackground(new java.awt.Color(248, 211, 94));
        btnxoaMaKM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaMaKM.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaMaKM.setText("Xóa");

        btnsuaMaKM.setBackground(new java.awt.Color(248, 211, 94));
        btnsuaMaKM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaMaKM.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaMaKM.setText("Sửa");

        javax.swing.GroupLayout jpnCard7Layout = new javax.swing.GroupLayout(jpnCard7);
        jpnCard7.setLayout(jpnCard7Layout);
        jpnCard7Layout.setHorizontalGroup(
            jpnCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard7Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCard7Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpnCard7Layout.createSequentialGroup()
                        .addComponent(jTextField7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuaMaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoaMaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthemMaKM))))
            .addComponent(jScrollPane7)
        );
        jpnCard7Layout.setVerticalGroup(
            jpnCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthemMaKM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7)
                    .addComponent(btnxoaMaKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaMaKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(575, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard7, "jpnListDis");

        jpnCard8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DANH SÁCH KHO");

        btnthemKho.setBackground(new java.awt.Color(244, 211, 94));
        btnthemKho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnthemKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        btnthemKho.setText("Thêm kho");

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Mã kho", "Trạng thái", "Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable8);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        btnxoaKho.setBackground(new java.awt.Color(248, 211, 94));
        btnxoaKho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnxoaKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        btnxoaKho.setText("Xóa");

        btnsuaKho.setBackground(new java.awt.Color(248, 211, 94));
        btnsuaKho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsuaKho.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        btnsuaKho.setText("Sửa");

        javax.swing.GroupLayout jpnCard8Layout = new javax.swing.GroupLayout(jpnCard8);
        jpnCard8.setLayout(jpnCard8Layout);
        jpnCard8Layout.setHorizontalGroup(
            jpnCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard8Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsuaKho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoaKho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthemKho))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpnCard8Layout.setVerticalGroup(
            jpnCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnthemKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsuaKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard8, "jpnListStock");

        jpnCard9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DANH SÁCH NHÂN VIÊN");

        jButton25.setBackground(new java.awt.Color(244, 211, 94));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton25.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\plus (6).png")); // NOI18N
        jButton25.setText("Thêm nhân viên");

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Mã nhân viên", "Mã nông trại", "Tên nhân viên", "Địa chỉ", "Số điện thoại", "Email", "Ngày vào làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable9);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\transparency.png")); // NOI18N

        jButton15.setBackground(new java.awt.Color(248, 211, 94));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\trash.png")); // NOI18N
        jButton15.setText("Xóa");

        jButton17.setBackground(new java.awt.Color(248, 211, 94));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\diuai\\Downloads\\pencil.png")); // NOI18N
        jButton17.setText("Sửa");

        javax.swing.GroupLayout jpnCard9Layout = new javax.swing.GroupLayout(jpnCard9);
        jpnCard9.setLayout(jpnCard9Layout);
        jpnCard9Layout.setHorizontalGroup(
            jpnCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCard9Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        jpnCard9Layout.setVerticalGroup(
            jpnCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard9, "jpnListEmp");

        jpnCard10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TRẠNG THÁI VẬN CHUYỂN");

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thất bại", "Thành công"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        javax.swing.GroupLayout jpnCard10Layout = new javax.swing.GroupLayout(jpnCard10);
        jpnCard10.setLayout(jpnCard10Layout);
        jpnCard10Layout.setHorizontalGroup(
            jpnCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnCard10Layout.setVerticalGroup(
            jpnCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCard10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(616, Short.MAX_VALUE))
        );

        jpnCardLayout.add(jpnCard10, "jpnListTrans");

        jpnCard11.setBackground(new java.awt.Color(248, 218, 208));

        javax.swing.GroupLayout jpnCard11Layout = new javax.swing.GroupLayout(jpnCard11);
        jpnCard11.setLayout(jpnCard11Layout);
        jpnCard11Layout.setHorizontalGroup(
            jpnCard11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jpnCard11Layout.setVerticalGroup(
            jpnCard11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jpnCardLayout.add(jpnCard11, "jpnListStatis");

        jSplitPane2.setRightComponent(jpnCardLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jbtManaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaProActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListPro");
        
    }//GEN-LAST:event_jbtManaProActionPerformed

    private void jbtManaFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaFarmActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListFarm");
    }//GEN-LAST:event_jbtManaFarmActionPerformed

    private void jbtManaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaOrderActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListOrder");
    }//GEN-LAST:event_jbtManaOrderActionPerformed

    private void jbtManaReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaReActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListRe");
    }//GEN-LAST:event_jbtManaReActionPerformed

    private void jbtManaSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaSupActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListSup");
    }//GEN-LAST:event_jbtManaSupActionPerformed

    private void jbtManaCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaCusActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListCus");
    }//GEN-LAST:event_jbtManaCusActionPerformed

    private void jbtManaDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaDisActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListDis");
    }//GEN-LAST:event_jbtManaDisActionPerformed

    private void jbtManaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaStockActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListStock");
    }//GEN-LAST:event_jbtManaStockActionPerformed

    private void jbtManaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaEmpActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListEmp");
    }//GEN-LAST:event_jbtManaEmpActionPerformed

    private void jbtManaTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaTransActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListTrans");
    }//GEN-LAST:event_jbtManaTransActionPerformed

    private void jbtManaStatisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtManaStatisActionPerformed
        // TODO add your handling code here:
        cardlayout.show(jpnCardLayout, "jpnListStatis");
    }//GEN-LAST:event_jbtManaStatisActionPerformed

    private void btnthemNongTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemNongTraiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemNongTraiActionPerformed

    private void btnxoaNongTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaNongTraiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaNongTraiActionPerformed

    private void btnxoaVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaVLActionPerformed

    private void btnxoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaNCCActionPerformed

    private void btnsuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuaNCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuaKH;
    private javax.swing.JButton btnsuaKho;
    private javax.swing.JButton btnsuaMaKM;
    private javax.swing.JButton btnsuaNCC;
    private javax.swing.JButton btnsuaNongTrai;
    private javax.swing.JButton btnsuaSP;
    private javax.swing.JButton btnsuaVL;
    private javax.swing.JButton btnthemKH;
    private javax.swing.JButton btnthemKho;
    private javax.swing.JButton btnthemMaKM;
    private javax.swing.JButton btnthemNCC;
    private javax.swing.JButton btnthemNongTrai;
    private javax.swing.JButton btnthemSP;
    private javax.swing.JButton btnthemVL;
    private javax.swing.JButton btnxoaKH;
    private javax.swing.JButton btnxoaKho;
    private javax.swing.JButton btnxoaMaKM;
    private javax.swing.JButton btnxoaNCC;
    private javax.swing.JButton btnxoaNongTrai;
    private javax.swing.JButton btnxoaSP;
    private javax.swing.JButton btnxoaVL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbtManaCus;
    private javax.swing.JButton jbtManaDis;
    private javax.swing.JButton jbtManaEmp;
    private javax.swing.JButton jbtManaFarm;
    private javax.swing.JButton jbtManaOrder;
    private javax.swing.JButton jbtManaPro;
    private javax.swing.JButton jbtManaRe;
    private javax.swing.JButton jbtManaStatis;
    private javax.swing.JButton jbtManaStock;
    private javax.swing.JButton jbtManaSup;
    private javax.swing.JButton jbtManaTrans;
    private javax.swing.JPanel jpnCard1;
    private javax.swing.JPanel jpnCard10;
    private javax.swing.JPanel jpnCard11;
    private javax.swing.JPanel jpnCard2;
    private javax.swing.JPanel jpnCard3;
    private javax.swing.JPanel jpnCard4;
    private javax.swing.JPanel jpnCard5;
    private javax.swing.JPanel jpnCard6;
    private javax.swing.JPanel jpnCard7;
    private javax.swing.JPanel jpnCard8;
    private javax.swing.JPanel jpnCard9;
    private javax.swing.JPanel jpnCardLayout;
    // End of variables declaration//GEN-END:variables
}
