-- Tao bang Inventory_Product
CREATE TABLE Inventory_Product
(
    stockID varchar2(10) NOT NULL,
    proID varchar2(10) NOT NULL, 
    num_Inventory_Pro number,
    
    CONSTRAINT PK_InvPro PRIMARY KEY(stockID, proID)
);
ALTER TABLE Inventory_Product ADD CONSTRAINT FK01_InvPro FOREIGN KEY(stockID) REFERENCES Stock(stockID);
ALTER TABLE Inventory_Product ADD CONSTRAINT FK02_InvPro FOREIGN KEY(proID) REFERENCES Product(proID);

-- Insert du lieu
INSERT INTO INVENTORY_PRODUCT VALUES ('S1', 'P1', 200);
INSERT INTO INVENTORY_PRODUCT VALUES ('S1', 'P2', 600);
INSERT INTO INVENTORY_PRODUCT VALUES ('S1', 'P3', 650);
INSERT INTO INVENTORY_PRODUCT VALUES ('S1', 'P4', 700);
INSERT INTO INVENTORY_PRODUCT VALUES ('S1', 'P5', 220);
INSERT INTO INVENTORY_PRODUCT VALUES ('S2', 'P1', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S2', 'P5', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S2', 'P7', 600);
INSERT INTO INVENTORY_PRODUCT VALUES ('S3', 'P6', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S3', 'P8', 550);
INSERT INTO INVENTORY_PRODUCT VALUES ('S3', 'P9', 200);
INSERT INTO INVENTORY_PRODUCT VALUES ('S3', 'P10', 320);
INSERT INTO INVENTORY_PRODUCT VALUES ('S4', 'P9', 200);
INSERT INTO INVENTORY_PRODUCT VALUES ('S4', 'P13', 280);
INSERT INTO INVENTORY_PRODUCT VALUES ('S4', 'P14', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S4', 'P15', 250);
INSERT INTO INVENTORY_PRODUCT VALUES ('S5', 'P6', 220);
INSERT INTO INVENTORY_PRODUCT VALUES ('S5', 'P9', 240);
INSERT INTO INVENTORY_PRODUCT VALUES ('S5', 'P10', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S5', 'P19', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S5', 'P20', 600);
INSERT INTO INVENTORY_PRODUCT VALUES ('S6', 'P11', 510);
INSERT INTO INVENTORY_PRODUCT VALUES ('S6', 'P12', 230);
INSERT INTO INVENTORY_PRODUCT VALUES ('S6', 'P13', 200);
INSERT INTO INVENTORY_PRODUCT VALUES ('S6', 'P15', 250);
INSERT INTO INVENTORY_PRODUCT VALUES ('S6', 'P16', 310);
INSERT INTO INVENTORY_PRODUCT VALUES ('S7', 'P12', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S7', 'P14', 220);
INSERT INTO INVENTORY_PRODUCT VALUES ('S7', 'P17', 350);
INSERT INTO INVENTORY_PRODUCT VALUES ('S8', 'P16', 400);
INSERT INTO INVENTORY_PRODUCT VALUES ('S8', 'P17', 300);
INSERT INTO INVENTORY_PRODUCT VALUES ('S8', 'P18', 590);
INSERT INTO INVENTORY_PRODUCT VALUES ('S8', 'P19', 300);