-- Tao bang OrderDetails_Ex
CREATE TABLE Order_Details_Ex
(
    ord_Ex_Num varchar2(10) not null,
    proID varchar2(10) not null,
    num_Products number,
    
    CONSTRAINT PK_CTHD_EX PRIMARY KEY(ord_Ex_Num, proID)
);

ALTER TABLE Order_Details_Ex ADD CONSTRAINT FK01_CTHD_EX FOREIGN KEY(ord_Ex_Num) REFERENCES Order_Export(ord_Ex_Num);
ALTER TABLE Order_Details_Ex ADD CONSTRAINT FK02_CTHD_EX FOREIGN KEY(proID) REFERENCES Product(proID);

-- Insert du lieu
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P1', 20);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P2', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P6', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P9', 60);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P15', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE1', 'P3', 20);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE2', 'P12', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE2', 'P5', 20);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE2', 'P15', 15);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE3', 'P2', 25);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE3', 'P6', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE3', 'P18', 40);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE3', 'P9', 45);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE4', 'P7', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE4', 'P11', 25);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE5', 'P20', 150);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE6', 'P2', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE6', 'P14', 40);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE6', 'P3', 35);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE6', 'P6', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE6', 'P12', 60);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE7', 'P10', 70);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE7', 'P7', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE7', 'P6', 35);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P8', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P20', 35);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P14', 60);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P17', 40);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P15', 30);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE8', 'P3', 50);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE9', 'P1', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE9', 'P4', 35);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE10', 'P8', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE10', 'P11', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE10', 'P15', 60);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE10', 'P19', 25);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE11', 'P10', 25);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE11', 'P12', 35);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE11', 'P20', 50);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE11', 'P17', 45);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE12', 'P1', 5);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE12', 'P4', 5);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE13', 'P6', 80);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE13', 'P9', 35);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE13', 'P10', 40);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE13', 'P13', 55);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE14', 'P15', 50);
		
INSERT INTO ORDER_DETAILS_EX VALUES ('OE15', 'P17', 350);
INSERT INTO ORDER_DETAILS_EX VALUES ('OE15', 'P20', 500);
