/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Customer;
import Model.Order_Export;
import Model.Product;
import Process.C_AdminHome;
import Process.C_Order_Details_Ex;
import Process.Customer_Controller;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author doquy
 */
public class PurchaseHistory extends javax.swing.JFrame {
    DefaultTableModel tableModelHistory, tableModelCTHD;
    String id_login;
    /**
     * Creates new form PurchaseHistory
     */
    public PurchaseHistory(String id) {
        initComponents();
        id_login = id;
        this.setLocationRelativeTo(null);
        jTablePurchaseHistory.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        jTablePurchaseHistory.getTableHeader().setOpaque(false);
        jTablePurchaseHistory.getTableHeader().setBackground(new Color(0, 179, 179));
        jTablePurchaseHistory.getTableHeader().setForeground(new Color(255, 255, 255));
        
        jTableCTHD.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTableCTHD.getTableHeader().setOpaque(false);
        jTableCTHD.getTableHeader().setBackground(new Color(197, 226, 255));
        jTableCTHD.getTableHeader().setForeground(new Color(0, 0, 0));
        
        tableModelHistory = (DefaultTableModel) jTablePurchaseHistory.getModel();
        tableModelCTHD = (DefaultTableModel) jTableCTHD.getModel();
        showTableHistory(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePurchaseHistory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCTHD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("LỊCH SỬ MUA HÀNG");
        jLabel1.setToolTipText("");

        jTablePurchaseHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePurchaseHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Mã vận đơn", "Trạng thái", "Địa chỉ nhận hàng", "Phương thức thanh toán", "Ngày mua hàng", "Trị giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePurchaseHistory.setFocusable(false);
        jTablePurchaseHistory.setRowHeight(30);
        jTablePurchaseHistory.setSelectionBackground(new java.awt.Color(255, 222, 131));
        jTablePurchaseHistory.setShowGrid(false);
        jTablePurchaseHistory.setShowVerticalLines(true);
        jTablePurchaseHistory.getTableHeader().setReorderingAllowed(false);
        jTablePurchaseHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePurchaseHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePurchaseHistory);
        if (jTablePurchaseHistory.getColumnModel().getColumnCount() > 0) {
            jTablePurchaseHistory.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTablePurchaseHistory.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTablePurchaseHistory.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTablePurchaseHistory.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTablePurchaseHistory.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/purchasing.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/return.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableCTHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên nông sản", "Giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCTHD.setFocusable(false);
        jTableCTHD.setRowHeight(25);
        jTableCTHD.setShowGrid(true);
        jTableCTHD.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTableCTHD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(395, 395, 395))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KH_Introduction1(id_login).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jTablePurchaseHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePurchaseHistoryMouseClicked
        // TODO add your handling code here:
        ArrayList<Product> arrLProPurchase;
        int selectedIndex = jTablePurchaseHistory.getSelectedRow();
        
        if (selectedIndex >= 0) {
            try {
                String maHD = jTablePurchaseHistory.getValueAt(selectedIndex, 0).toString();
                arrLProPurchase = C_Order_Details_Ex.timCTHD(maHD);
                tableModelCTHD.setRowCount(0);
                for (Product p : arrLProPurchase) {
                    tableModelCTHD.addRow(new Object[]{tableModelCTHD.getRowCount() + 1, p.getProName(), 
                                                                                        p.getProPrice(), p.getQuantity()});
                }
                tableModelCTHD.fireTableDataChanged();
                
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(PurchaseHistory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTablePurchaseHistoryMouseClicked

    
    public void showTableHistory(String id) {
        try {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            ArrayList<Order_Export> listOrderHistory;
            String trangThaiVanChuyen;
            
            listOrderHistory = Customer_Controller.historyPurchase(id);
            tableModelHistory.setRowCount(0);
            
            for (Order_Export oe : listOrderHistory) {
               if (oe.getTransID() != null) {
                    switch (oe.getStatusTrans()) {
                        case 0:
                            trangThaiVanChuyen = "Thất bại";
                            break;
                        case 1:
                            trangThaiVanChuyen = "Thành công";
                            break;
                        default:
                            trangThaiVanChuyen = "Đang giao hàng";
                            break;
                    }
                }else{
                    trangThaiVanChuyen = "Thành công";
                }

                tableModelHistory.addRow(new Object[]{oe.getOrd_Ex_Num(), oe.getTransID(), trangThaiVanChuyen, oe.getDeli_Address(),
                    oe.getPayBy(), f.format(oe.getDateOrdered()), oe.getOrderTotal()});
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(PurchaseHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCTHD;
    private javax.swing.JTable jTablePurchaseHistory;
    // End of variables declaration//GEN-END:variables
}
